Exception
	프로그램이 실행 중에 발생되는 에러를 그냥 아무런 처리도 하지않으면 강제 종료가 됨
	프로그램을 강제로 종료가 되지 않게끔 처리하기 위해서,
	Exception을 이용해서 중간에 에러가 발생한 것을 잡아서 처리하고, 코드를 계속 이어서 작업하게끔 하는 처리방법 
	
try : 작업영역, 대신에 이 영역에서는 Exception이 발생할 수 있다.
catch : try 영역에서 Exception이 발생 했을때 Exception을 처리하는 영역
finally : 
throw : 
throws :
